### ISSUE TITLE
Other user's text is same colour as their bubble

### ISSUE THREAD

**Issue by B4ttleCat** [messengerblack/messengerblack-safari#4]
Looks like this was attempted to be fixed in the past two releases but I've just downloaded the extension and am not seeing the other person's message text. Safari 15.1 on macOS 11.6.1
<img width="211" alt="CleanShot 2022-01-23 at 22 38 41" src="https://user-images.githubusercontent.com/3996204/150676585-f3f0d5f7-d82e-465f-b489-2912c56b2be9.png">
.

**Comment by ryanmohta** [comment]
Thanks for the issue! Sorry for the extremely late reply, I’m actually a college student and finally had time to work on this after my recent quarter ended. I’ve just pushed a fix in a PR and linked that PR to this issue, so when I merge the PR this issue will be closed automatically. Expect to see an update with the change fixed on the Mac App Store and Chrome Web Store in the next few days!

**Comment by B4ttleCat** [comment]
Hey, no need to apologise, Ryan! Thanks for the fix, look forward to it hitting the store. Sorry if this reopens it. Take care!
